[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"

[[deploy.include]]
path = "routes"

[[deploy.include]]
path = "models"

[[deploy.include]]
path = "services"

[[deploy.include]]
path = "socket"

[[deploy.include]]
path = "ai-core"

[[deploy.include]]
path = "shared"